version: '3.9'
services:
  library:
    container_name: library
    build:
      context: ./
      dockerfile: Dockerfile
    command: /bin/sh -c "go run main.go"
    volumes:
      - .:/app
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - POSTGRES_DSN=host=library_db user=postgres password=1234 dbname=library port=5432 sslmode=disable TimeZone=Asia/Bangkok
      - REDIS_HOST=library_redis
      - REDIS_PORT=6379
    depends_on:
      - library_db
      - library_redis
  
  library_db:
    container_name: library-db
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=library
      - POSTGRES_PASSWORD=1234
    volumes:
      - ./data/postgres:/data/db
  
  library_redis:
    container_name: library-redis
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data

